name: CD to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud (Docker)
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin northamerica-northeast1-docker.pkg.dev

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev --quiet

      - name: Build and push Docker image
        env:
          IMAGE_URI: northamerica-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/airfrance/fastapi-app:latest
        run: |
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy to Cloud Run
        env:
          IMAGE_URI: northamerica-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/airfrance/fastapi-app:latest
        run: |
          gcloud run deploy fastapi-service \
            --image "$IMAGE_URI" \
            --region northamerica-northeast1 \
            --platform managed \
            --allow-unauthenticated \
            --timeout 300 \
            --memory 1Gi \
            --cpu 2

