name: CD to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev

      - name: Build and push Docker image
        env:
          IMAGE_URI: northamerica-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/airfrance/fastapi-app:latest
        run: |
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy to Cloud Run
        env:
          IMAGE_URI: northamerica-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/airfrance/fastapi-app:latest
        run: |
          gcloud run deploy my-fastapi-service \
            --image $IMAGE_URI \
            --region northamerica-northeast1 \
            --allow-unauthenticated
